name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: |
        composer install --no-progress --ignore-platform-req=ext-mongodb

    - name: Build
      run: |
        npm install
        npm run build-prod

    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: -avzr --delete --exclude=".git/*"
        path: src/
        remote_path: ~/
        remote_host: spotify.daselias.at
        remote_port: 1717
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
